fd:
  microservice:
    user:
      name: fd-user-service

spring:
  application:
    name: fd-user-feign-client

server:
  port: 8080

eureka:
  server:
    host: localhost:8761
    contextPath: serviceregistry
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.server.host}/${eureka.server.contextPath}/eureka}
  instance:
    preferIpAddress: true