fd:
  microservice:
    user:
      name: fd-user-service

spring:
  application:
    name: fd-user-feign-client
  cache:
    redis:
      cache-null-values: false
      time-to-live: 10000
      use-key-prefix: true
  redis:
    host: localhost
    port: 6379
    timeout: 200

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    ROOT: INFO
    org.spring.framework: ERROR
    com.fd: TRACE
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss} - %msg%n"

