server:
  port: 8080
  servlet:
    contextPath: /serviceregistry

eureka:
  instance:
    hostname: registry
    appname: registry-cluster
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/serviceregistry/eureka/

spring:
  application:
    name: registry-cluster