spring:
  application:
    name: fd-user-service

server:
  port: 9091
  servlet:
    contextPath: /test

eureka:
  server:
    host: localhost:8761
    contextPath: serviceregistry
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.server.host}/${eureka.server.contextPath}/eureka}
  instance:
    preferIpAddress: true