spring:
  application:
    name: fd-user-service

server:
  port: 9091
  servlet:
    contextPath: /test

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true